---

- hosts: all
  become: true
  tasks:

  - name: install the apache and php  package
    apt:
      name: 
        - apache2 
        - libapache2-mod-php   
      state: latest
      update_cache: yes
    when: ansible_distribution in ['Ubuntu','SparkyLinux']

  - name: install apache and php in fedora
    dnf: 
      name: 
       - httpd
       - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ['Fedora']

