---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ['Ubuntu','SparkyLinux'] 

  - name: install the apache2 and php  package
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
    when: ansible_distribution in ['Ubuntu','SparkyLinux']


  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ['Fedora'] 

  - name: install the apache2 and php package
    dnf:
      name: 
        - httpd
        - php  
      state: latest
    when: ansible_distribution in ['Fedora']
