---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (centOS)
    tags: always
    dnf:
#    update_only: yes -> done in bootstrap
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ['Fedora']

  - name: update repo cache (Lubuntu, Sparky)
    tags: always
    apt:
#    upgrade: dist -> done in bootstrap
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ['Ubuntu','SparkyLinux']

- hosts: all
  become: true
  tasks:
      
  - name: add ssh key for simona
    tags: always
    authorized_key: 
      user: simona
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILE2ir7LNVmxR7bPKOUAFdcwknQ0s5yERk42g6yctDh9 ansible"
  
  

- hosts: web_servers
  become: true
  tasks:

  - name: install the apache and php  package
    tags: apache,apache2,ubuntu 
    apt:
      name: 
        - apache2 
        - libapache2-mod-php   
      state: latest
    when: ansible_distribution in ['Ubuntu','SparkyLinux']

  - name: install apache and php in fedora
    tags: apache,centOS,httpd
    dnf: 
      name: 
       - httpd
       - php
      state: latest
    when: ansible_distribution in ['Fedora']

  - name: start httpd (Fedora)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution in ['Fedora']

  - name: change e-mail address of admin
    tags: apache,centos,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin qualcuno@somewhere.net
    when: ansible_distribution in ['Fedora']
    register: httpd

  - name: restart httpd (Fedora)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed


  - name: copy default html file for site
    tags: apache,apache2,ubuntu
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode:  0644

- hosts: db_servers
  become: true
  tasks:
    
  - name: install maridb package (CentoOS)
    tags: centOS,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution in ['Fedora']

  - name: install mariadb package (lubuntu, sparkylinux)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ['Ubuntu','SparkyLinux']    
