---

- hosts: all
  become: true
  tasks:

  - name: install the apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ['Ubuntu','SparkyLinux']

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ['Ubuntu','SparkyLinux']
